name: CMake

on:
    - push
    - pull_request

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: 'recursive'
            - uses: lukka/get-cmake@latest
            - uses: lukka/run-vcpkg@v10
            - name: CMake Configure
              run: |
                  mkdir build
                  cd build
                  cmake -DCMAKE_TOOLCHAIN_FILE:STRING=./vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET:STRING=x64-windows-static-md -G "Visual Studio 17 2022" -T host=x64 -A x64 ..
            - name: CMake Build
              run: cmake --build build --config MinSizeRel
            - uses: actions/upload-artifact@v3.1.1
              with:
                  name: cocogoat-control-uncompressed
                  path: build/MinSizeRel/*.exe
            - uses: crazy-max/ghaction-upx@v2
              with:
                version: latest
                files: build/MinSizeRel/*.exe
            - uses: actions/upload-artifact@v3.1.1
              with:
                  name: cocogoat-control
                  path: build/MinSizeRel/*.exe
